### ISSUE TITLE
[BUG] Search not finding tabs that were snoozzed in a group

### ISSUE THREAD

**Issue by Mansarde** [rohanb10/snoozz-tab-snoozing#62]
## Description
The search doesn't seem find tabs that are within a group of tabs that were snoozzed together.

## Expected Behavior
When I search for a tab that is within a group of tabs (that were snoozeed together) I would expect the results to show at least the group it is a part of.

## Actual Behavior
No results are shown (as if the tab does not exist).

## How to Reproduce (if applicable)
Snoozz a group of tabs and then try to search for only one of the tabs.

## Your Device
* Browser and version: Brave V1.30.89 (Chromium 94.0.4606.81) 64-Bit
* OS: Windows 10 Pro, 21H1, Build 19043.1288

## Which Page
Sleeping Tabs page

## Screenshots / Videos / Logs
![image](https://user-images.githubusercontent.com/847687/137632327-32439ebf-d45e-4831-a754-f4643af5a894.png)
![image](https://user-images.githubusercontent.com/847687/137632332-636ba8dc-fb71-4b46-8006-80223c40293b.png)

**Comment by rohanb10** [comment]
Wow that's actually a pretty glaring in the search feature. I have just pushed up a new commit 16240804613e5769f57439097eccb4c7dc6e3cd0 with a fix for this. I'll aim to release it later this week

**Comment by Mansarde** [comment]
Thanks for the quick fix!
Glad I could help out. Really love the extension, one of my favorite daily drivers. 🙂👍

**Comment by polanar** [comment]
This still isn't working here. Search doesn't find anything that exists within groups of snoozed tabs.

**Comment by Mansarde** [comment]
@polanar There hasn't been a new release since the problem was reported, so the fix is not included yet.
Maybe the author was just very busy or forgot about it. Hopefully he'll make a new release soon. 🤞😁🤞

P.S.: Happy new year! 🥳

EDIT: Btw. I'm using local overrides in the DevTools of Chrome to include the fix from the commit the author mentioned above. The only downside is that I have to open and close the DevTools once I have the sleeping-tabs page open (for the override to become active), but that just requires hitting F12 two times, so it's an acceptable workaround for me in the meantime.^^
